# Generated by Django 6.0.2 on 2026-02-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='unknown', max_length=100, unique=True),
        ),
    ]
