# Generated by Django 6.0.2 on 2026-02-19 07:00

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers_user_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.CustomManager()),
                ('all_objects', user.models.AllObjectsUserManager()),
            ],
        ),
    ]
