# Generated by Django 6.0.2 on 2026-02-22 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_author_alter_imagebook_book'),
        ('user', '0004_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='unknown', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', related_query_name='back', to='book.book'),
        ),
    ]
