# Generated by Django 6.0.2 on 2026-02-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_author_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author'},
        ),
        migrations.AddField(
            model_name='author',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
