# Generated by Django 6.0.2 on 2026-02-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_author_options_author_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
