# Generated by Django 6.0.2 on 2026-02-24 11:47

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('all_objects', user.models.AllObjectsUserManager()),
                ('objects', user.models.CustomManager()),
            ],
        ),
    ]
