# Generated by Django 6.0.2 on 2026-02-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagebook',
            options={'verbose_name_plural': 'Images of books'},
        ),
    ]
