# Generated by Django 6.0.2 on 2026-02-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_imagebook_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='imagesQuery', to='book.book'),
        ),
    ]
