# Generated by Django 6.0.2 on 2026-02-19 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_imagebook_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagebook',
            options={'verbose_name': 'Images of books'},
        ),
        migrations.AlterField(
            model_name='imagebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image_query', to='book.book'),
        ),
    ]
