# Generated by Django 6.0.2 on 2026-02-19 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_imagebook_options_alter_imagebook_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiffrentBook',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book'},
        ),
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='book_query', to=settings.AUTH_USER_MODEL),
        ),
    ]
