# Generated by Django 6.0.2 on 2026-02-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_delete_diffrentbook_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
