# Generated by Django 6.0.2 on 2026-02-23 12:20

import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagebook',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='image_book',
            field=models.ManyToManyField(related_name='books', to='book.imagebook'),
        ),
        migrations.AddField(
            model_name='imagebook',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='imagebook',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='imagebook',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
    ]
