# Generated by Django 6.0.2 on 2026-02-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_imagebook_book_book_image_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagebook',
            name='image_ppoi',
        ),
        migrations.AlterField(
            model_name='imagebook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagebook',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
