# Generated by Django 6.0.2 on 2026-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_options_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('MT', 'math'), ('SC', 'science'), ('HS', 'history')], db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_book',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='book.imagebook'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
