# Generated by Django 6.0.2 on 2026-02-26 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_category_alter_book_image_book_and_more'),
        ('user', '0011_alter_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='query_books', to='user.author'),
        ),
    ]
